package com.apiscan.report;

import com.apiscan.domain.SecurityScan;
import com.apiscan.domain.Vulnerability;
import com.apiscan.repository.SecurityScanRepository;
import com.apiscan.repository.VulnerabilityRepository;
import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import jakarta.persistence.EntityNotFoundException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Slf4j
@Service
@RequiredArgsConstructor
public class PdfExportService {

    private final SecurityScanRepository scanRepository;
    private final VulnerabilityRepository vulnerabilityRepository;

    private static final Font TITLE_FONT = new Font(Font.HELVETICA, 20, Font.BOLD, new Color(33, 37, 41));
    private static final Font HEADER_FONT = new Font(Font.HELVETICA, 14, Font.BOLD, new Color(52, 58, 64));
    private static final Font BODY_FONT = new Font(Font.HELVETICA, 10, Font.NORMAL, new Color(73, 80, 87));
    private static final Font TABLE_HEADER_FONT = new Font(Font.HELVETICA, 10, Font.BOLD, Color.WHITE);

    public byte[] generatePdf(String scanId) {
        SecurityScan scan = scanRepository.findById(scanId)
                .orElseThrow(() -> new EntityNotFoundException("Scan not found"));
        List<Vulnerability> vulns = vulnerabilityRepository.findAllByScanId(scanId);

        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4, 50, 50, 50, 50);
            PdfWriter.getInstance(doc, out);
            doc.open();

            // Title
            Paragraph title = new Paragraph("APIScan Security Report", TITLE_FONT);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            doc.add(title);

            // Scan info
            doc.add(new Paragraph("Target: " + scan.getTargetUrl(), BODY_FONT));
            doc.add(new Paragraph("Method: " + scan.getMethod(), BODY_FONT));
            doc.add(new Paragraph("Status: " + scan.getStatus(), BODY_FONT));
            doc.add(new Paragraph("Date: " + scan.getCreatedAt().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME),
                    BODY_FONT));
            if (scan.getDurationMs() != null) {
                doc.add(new Paragraph("Duration: " + scan.getDurationMs() + "ms", BODY_FONT));
            }
            doc.add(new Paragraph(" "));

            // Summary
            doc.add(new Paragraph("Vulnerabilities Found: " + vulns.size(), HEADER_FONT));
            doc.add(new Paragraph(" "));

            if (!vulns.isEmpty()) {
                // Vulnerability table
                PdfPTable table = new PdfPTable(new float[] { 15, 15, 40, 30 });
                table.setWidthPercentage(100);

                addTableHeader(table, "Type", "Severity", "Description", "Remediation");

                for (Vulnerability v : vulns) {
                    table.addCell(createCell(v.getType()));
                    table.addCell(createSeverityCell(v.getSeverity().name()));
                    table.addCell(createCell(v.getDescription()));
                    table.addCell(createCell(v.getRemediation() != null ? v.getRemediation() : "N/A"));
                }

                doc.add(table);
            } else {
                doc.add(new Paragraph("No vulnerabilities were detected.", BODY_FONT));
            }

            // Footer
            doc.add(new Paragraph(" "));
            Paragraph footer = new Paragraph("Generated by APIScan — API Security Testing Platform", BODY_FONT);
            footer.setAlignment(Element.ALIGN_CENTER);
            doc.add(footer);

            doc.close();
            return out.toByteArray();

        } catch (Exception e) {
            log.error("PDF generation failed for scan {}: {}", scanId, e.getMessage(), e);
            throw new RuntimeException("Failed to generate PDF report", e);
        }
    }

    private void addTableHeader(PdfPTable table, String... headers) {
        for (String header : headers) {
            PdfPCell cell = new PdfPCell(new Phrase(header, TABLE_HEADER_FONT));
            cell.setBackgroundColor(new Color(52, 58, 64));
            cell.setPadding(8);
            table.addCell(cell);
        }
    }

    private PdfPCell createCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text != null ? text : "", BODY_FONT));
        cell.setPadding(6);
        return cell;
    }

    private PdfPCell createSeverityCell(String severity) {
        Color bg = switch (severity) {
            case "CRITICAL" -> new Color(220, 53, 69);
            case "HIGH" -> new Color(255, 128, 0);
            case "MEDIUM" -> new Color(255, 193, 7);
            case "LOW" -> new Color(23, 162, 184);
            default -> new Color(108, 117, 125);
        };
        Font font = new Font(Font.HELVETICA, 10, Font.BOLD, Color.WHITE);
        PdfPCell cell = new PdfPCell(new Phrase(severity, font));
        cell.setBackgroundColor(bg);
        cell.setPadding(6);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        return cell;
    }
}
